### ISSUE TITLE
home 화면 기능 개발

### ISSUE THREAD

**Issue by seiyoon** [mrgentle1/Plog-Seoul#40]
## Description
5월 18일까지 개발할 홈화면 관련 내용들입니다.

## Todo

- [x] 계절별 코스 화면 클릭 시 화면 이동
- [x] 계절별 코스 api 연결하기
- [x] point 값에 따라 프로그레스 바 길이 조절되게 하기
