### ISSUE TITLE
course 화면 기능 개발

### ISSUE THREAD

**Issue by seiyoon** [mrgentle1/Plog-Seoul#44]
## Description
코스 화면과 관련된 기능들

## Todo

- [x] 이미지 슬라이드 추가
- [x] 이미지 슬라이드에 코스 사진들 api 연결
- [x] 리뷰 작성 시 100포인트 적립되게 하기
- [x] 수정/삭제 api 연결이 약간 이상한데 그 부분 고치기
- [x] CoursePostPage.js의 ReviewCard 수정하기
