### ISSUE TITLE
Course Screen

### ISSUE THREAD

**Issue by seiyoon** [mrgentle1/Plog-Seoul#5]
## Description
코스보기 화면

## Todo

- [x] 코스보기 화면 레이아웃
- [x] 화면별 연결
- [x] 코스 리뷰 화면
- [x] header에 검색 버튼 두는 조건 걸기
