### ISSUE TITLE
Walk-main Screen

### ISSUE THREAD

**Issue by ancy0** [mrgentle1/Plog-Seoul#6]
## Description
기록하기 메인화면. 지도에 현재 사용자의 위치 표시. 

## Todo

- [x] 기본 UI
- [x] kakao map api 화면에 불러오기
- [x] 사용자 위치 표시
- [x] 위치 재조정 
- [x] 시작하기 버튼 클릭 시 화면 이동
