### ISSUE TITLE
0601 확인된 이슈

### ISSUE THREAD

**Issue by mrgentle1** [mrgentle1/Plog-Seoul#75]
## Todo

- [x] 캘린더에서 전월 데이터가 안보이는 문제
- [x] 기록하기 빠르게 시작 시 이상한 위치에서 시작하는 문제
- [ ] 앱이 비정상적으로 종료되었을 시 기록 재개 또는 삭제 처리
- [ ] 오랫동안 기록하던 상태에서 사진 촬영 시 앱이 종료되는 현상
- [ ] 지도에서 쓰레기통 표시를 키고, X버튼 누르면 렉걸리는 문제
- [x] 포인트 전환 시 레벨이 감소함 -> 서버에서 1000포인트마다 레벨업 처리 후 -1000포인트 로직 삭제 필요
- [ ] 사진 공유하기 시 파이어베이스 업로드 -> 파이어베이스 다운로드 -> 파이어베이스 삭제 과정 때문에 너무 오래걸림. 웹에서 바로 파일을 다운로드 할 수 있도록 로직 수정
